### ISSUE TITLE
Export action?

### ISSUE THREAD

**Issue by kewball** [Reeywhaar/tabsaver#13]
I'd really like to export from tabsaver
```
async export() {
				await browser.runtime.sendMessage("export");
},
```

**Comment by reeywhaar** [comment]
I'm not sure what you mean? I have button to export data as json, is this what you need?

![screenshot 2019-01-16 at 06 39 23](https://user-images.githubusercontent.com/884649/51225402-765c7580-195b-11e9-83f6-99d704e39d4f.png)

**Comment by reeywhaar** [comment]
I'm closing, but if I haven't guessed what you meant, feel free to let me know

**Comment by kewball** [comment]
Oh. My mistake; I was looking in the wrong place for the export function. Thanks.
