### ISSUE TITLE
tabsaver feature request

### ISSUE THREAD

**Issue by Mister-Private** [Reeywhaar/tabsaver#2]
I love this web extension! SO helpful. I have two ideas. Confirmation dialogs for save and delete would be great. Second, "add" and "subtract"; an "add" button that adds the currently active tab to the currently active set would be cool. And the converse, a "subtract" button that deletes an individual URL from the set.

**Comment by reeywhaar** [comment]
Dear @Mister-Private, thank you for your suggestions.
I think confirmation dialogs are not necessary, it's all just ux noize for me. I'd rather think about undo functionality.
As for add/subtract, I personally think it will lead to another one bookmarks graveyard as with regular bookmarks, but I'm all open for PRs or forks.
Neither of above is a strong opinion, just personal thoughts which can change.

**Comment by Mister-Private** [comment]
I do think there should be some means to stop/check deletions or changing of sets. In setting up my Tab Sets, I hit the Save when I thought I was hitting Open and also "x" when I thought I was hitting Save. Maybe it's me and my fast, inaccurate mousing, but it was frustrating. 

The add/subtract just seems like a no-brainer to me. I often have windows of specific subjects (Social Media for example) where the tabs change over time (weeks). To name and save a new tab set and then delete the old tab set to get the latest seems like more work than necessary. Maybe I'm not understanding the functionality of Tab Saver.
