### ISSUE TITLE
Do not see option for saving tabs

### ISSUE THREAD

**Issue by cotupha** [Reeywhaar/tabsaver#22]
I only see the options for reloading or deleting a tab.
I went over the configuration and I didn't see anything that would solve it.
What am I missing?

Please find attached a screenshot of what I'm seeing.

![Screenshot from 2021-02-03 08-50-56](https://user-images.githubusercontent.com/1775413/106766174-37132700-65ff-11eb-8d4b-fe1346cc8c58.png)

Running on FF 85.0 (64 bit) for Ubuntu canonical - 1.0

**Comment by reeywhaar** [comment]
What do you mean by "saving" a tab? Options you see are correct. If you want to save group of tabs, you can click on "plus" button, either on top or on window header (visible on hover).

<img width="339" alt="image" src="https://user-images.githubusercontent.com/884649/109673560-3383a900-7b87-11eb-9780-6d106a9270cd.png">

Hope it helps :-)
