### ISSUE TITLE
Can't open tab in private windows

### ISSUE THREAD

**Issue by Crikxi** [Reeywhaar/tabsaver#28]
When I try to open a tab in a private window, nothing happens.
After looking, at the debugging console, I have an error : "Uncaught (in promise) Error: Illegal to set non-private cookieStoreId in a private window".
The error comes from the function openURL of shared.js, more especially at the line 172 : 

```js
return await browser.tabs.create({
        url: getMangledURL(url),
        cookieStoreId, // equals to firefox-default
});
```

Then there is the catch but the error doesn't correspond to the if condition.

Maybe, we can check the error in the catch, and open the tab with the cookieStoreId equals to PRIVATE_COOKIE_STORE_ID (set in the top of the file).

Thank you in advance for your help.

**Comment by reeywhaar** [comment]
Fixed with your PR :-) https://github.com/Reeywhaar/tabsaver/pull/29
