### ISSUE TITLE
Installable but broken on firefox android

### ISSUE THREAD

**Issue by twidi** [Reeywhaar/tabsaver#3]
This extension can be installed on firefox andriod.
There is then a "Tab saver" entry in the menu, which leads to a page where I can create a tabset but... sadly, everything I try says "some error occured"

It would be very great to have this working on firefox android, because it's not so rare to have all the tabs wiped out (and there is no session manager compatible with firefox android)

**Comment by reeywhaar** [comment]
Oh, @twidi, thanks for report. I would like to help, but I don't have any android device to debug with. I think the problem there is trivial, so if there is anyone who could provide me with info*, or make pull request maybe, it will be greatly appreciated.

For now I think I'll uncheck compatibility with FF for Android on amo. If there is someone who would like to test future releases on Android, It will be a great help.

\* If name of the error is "Some error occured", then there must be full error in the browser console. Read the [Using WebIDE to debug your extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android#Using_WebIDE_to_debug_your_extension) manual, to get access to the browser console.

**Comment by reeywhaar** [comment]
Well, I found that browser.windows API is not available on android (why?), thus, it means that my extension can't work, until such API will be provided. Sorry.

**Comment by twidi** [comment]
Sad but thanks. Thanks but sad.

Keep up the good work!
