### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by haldente** [Reeywhaar/tabsaver#32]
Hi I've been using Tab Saver for 3 years now ok but now when I click the icon it will no longer load.

Tried disabling other Extensions and restarting but no dice.

It had a lot of long entries. Perhaps some limit was reached? Last thing that worked was adding an entry. I would try reinstall but I think I would lose entries for good.

Where does Tab Saver strore URL data?

Firefox 102.0
Win 7 Home Premium

Thank you

**Comment by reeywhaar** [comment]
Tab Saver stores data in browser storage. To be precise it is local browser storage.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local

The way to restore data it is to restore firefox profile from backup, and then try to export tabs via TabSaver preferences. Then tabs can be reimported.
![image](https://user-images.githubusercontent.com/884649/179375274-34b1c026-31d4-49af-af37-20f40ccfcaf7.png)

Profile location can be found by typing "about:support" into URL bar, then by searching for "Profile Folder".

**Comment by NLS24** [comment]
I am having the same issue. The solution above did not work. when trying to open a tab set, it says "some error occurred"
Any suggestions?

**Comment by reeywhaar** [comment]
Close as stale
