### ISSUE TITLE
Tester/Assistant for "Firefox for Android" wanted.

### ISSUE THREAD

**Issue by Reeywhaar** [Reeywhaar/tabsaver#4]
Hi! If you have skills to debug and test extensions on "Firefox for Android" and would like to contribute to this webextension, your help will be highly appreciated, as I don't have android device myself, and just blindly trust that there is no differences with desktop Firefox.

Leave the comments below, and look on open issues tagged with "[FF on Android](/Reeywhaar/tabsaver/issues?q=is%3Aissue+is%3Aopen+label%3A"FF+on+Android")"

Thank you!

**Comment by reeywhaar** [comment]
Well, just now I understood, that there is no possible way extension can work on Android.
