### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist 

### ISSUE THREAD

**Issue by The4Apes** [Reeywhaar/tabsaver#41]
Since today i get the error "Could not establish connection. Receiving end does not exist " if i try add or delete any tab from any tabset.
If i try to save a new tab set,  i get the error "Some error occred".
I would have tried do delete an reinstall the extension, but the button "Export TabSets" do not work.
Yesterday everything was fine and I didn't change anything.
What a mess.

Windows 10 22H2 with Firefox 127.0.2 (64-Bit)

I just see the extension was updated today to version 0.2.5 and 0.2.6, so there is a Bug in your code.
Until then I will continue to use the latest working version 0.2.4.

**Comment by reeywhaar** [comment]
Released 0.2.7 which is 0.2.4 that seems to be working. Sorry for inconvenience.
