### ISSUE TITLE
Stopped working 25 June 2023

### ISSUE THREAD

**Issue by NLS24** [Reeywhaar/tabsaver#42]
Thank you for a wonderful plug-in! It has overtime helps me with organisation and efficiency. Keep up the good work!

But for some reason, it suddenly stopped working? My guess it has to do with the 0.2.6 update. Or maybe even that, 0.2.5?
Finally, I figured out how to downgrade to 0.2.4 with Time Machine... seems to work... (not the easiest process, figuring out where this extension lives and the actual name of the actual extension file. So I just took all of them and restored to an older back up, resulting in downgrading the version)
Any suggestions on how to get 0.2.6 to run without receiving the "some error occurred" message? = no tabs set opens.

I am running Firefox 127.0.2 (64-bit) on Mac M1

If anyone else decides to do what I did remember to turn off the automatic update as soon as possible for this extension. Otherwise you're gonna have the same issue all over again.

**Comment by reeywhaar** [comment]
Huh, it really stopped. Would check it out asap, sorry for the inconvenience!

**Comment by reeywhaar** [comment]
Released 0.2.7 which should fix the issue

**Comment by NLS24** [comment]
😘
